- name: "Setup POD network"
  with_items: "{{ groups['k8s_master'] }}"
  when: hostvars[item]['k8sjoincommand'].stdout is defined
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
