#!/usr/bin/env python3

import os
import json
import requests

if (os.environ.get('CONSUL_HTTP_SSL') == 'true'):
    consulProto = "https://"
else:
    consulProto = "http://"

url = consulProto + os.environ.get("CONSUL_HTTP_ADDR") + "/v1/catalog/services"

services_json = json.loads(requests.request("GET", url).text)

inventory = { }

for host in services_json.keys():
    for tag in services_json[host]:
        if tag in inventory.keys():
            inventory[tag].append(host)
        else:
            inventory.update( { tag: [ host ] } )

print(json.dumps(inventory))