- name: "Init K8s"
  shell: kubeadm init --pod-network-cidr={{ lookup('community.general.hashi_vault', "secret=secret/data/k8s_config/master_node_config:pod_cidr_network ca_cert={{ lookup('env', 'VAULT_CAPATH') }}") }}
  args:
    creates: /etc/kubernetes/admin.conf
  register: k8sinit

- name: "Init K8s - Debug"
  when: k8sinit.stdout is defined
  debug:
    msg: "{{ k8sinit.stdout }}"
  
- name: "Get k8s join command"
  shell: kubeadm token create --print-join-command
  when: k8sinit is defined
  register: k8sjoincommand
