- name: "Wait for target to become available if needed"
  wait_for_connection:

- name: "Gather facts"
  setup:

- name: "Init K8s"
  shell: kubeadm init --pod-network-cidr={{ lookup('community.general.hashi_vault', "secret=secret/data/k8s_config/master_node_config:pod_cidr_network ca_cert={{ lookup('env', 'VAULT_CAPATH') }}") }}
  args:
    creates: /etc/kubernetes/admin.conf
  when: "'mkube' in inventory_hostname"
  register: k8sinit

- name: "Init K8s - Debug"
  when: k8sinit.stdout is defined
  debug:
    msg: "{{ k8sinit.stdout }}"
  
- name: "Get k8s join command"
  shell: kubeadm token create --print-join-command
  when: k8sinit is defined and inventory_hostname | regex_search ("^mkube.*", ingnore_case=True)
  register: k8sjoincommand

- name: "Join Workers to k8s cluster - debug"
  when: hostvars['mkube01']['k8sjoincommand'].stdout is defined and inventory_hostname | regex_search ("^kube.*", ingnore_case=True)
  with_items: "{{ hostvars['mkube01']['k8sjoincommand'].stdout }}"
  debug:
    msg: "{{ hostvars['mkube01']['k8sjoincommand'].stdout }}"
  
- name: "Join Workers to k8s cluster"
  when: hostvars['mkube01']['k8sjoincommand'].stdout is defined and inventory_hostname | regex_search ("^kube.*", ingnore_case=True)
  with_items: "{{ hostvars['mkube01']['k8sjoincommand'].stdout }}"
  shell: "{{ hostvars['mkube01']['k8sjoincommand'].stdout }}"
