- name: "Wait for target to become available if needed"
  wait_for_connection:

- name: "Gather facts"
  setup:

- name: "Install NFS Software"
  yum:
    name: nfs-utils
    state: present

- name: "Create nfs data filesystem"
  community.general.filesystem:
    fstype: xfs
    dev: /dev/xvdb

- name: "Create nfs data mountpoint"
  file:
    path: /nfs_data
    state: directory
    owner: root
    group: root
    mode: 0700

- name: "Create nfs data mount"
  ansible.posix.mount:
    path: /nfs_data
    src: /dev/xvdb
    fstype: xfs
    state: mounted

- name: "Disable Firewall"
  service:
    name: firewalld
    state: stopped
    enabled: no

